apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    [smtp]
    enabled=true
    host=smtp.gmail.com:587
    user=xambalay.do@gmail.com
    password=xambalay@0991
    from_address=xambalay.do@gmail.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"grafana.ini":"[analytics]\ncheck_for_updates = true\n[grafana_net]\nurl = https://grafana.net\n[log]\nmode = console\n[paths]\ndata = /var/lib/grafana/\nlogs = /var/log/grafana\nplugins = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n[server]\ndomain = ''\n[smtp]\nenabled=true\nhost=smtp.gmail.com:587\nuser=dupatrick84@gmail.com\npassword=1999naissance\nfrom_address=dupatrick84@gmail.com\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"my-release","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2024-05-29T18:59:19Z","labels":{"app.kubernetes.io/instance":"my-release","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"10.4.1","helm.sh/chart":"grafana-7.3.11"},"name":"my-release-grafana","namespace":"default","resourceVersion":"26116","uid":"2288c75a-74d2-480a-8e5a-8f35fdc475c7"}}
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-05-29T18:59:19Z"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.1
    helm.sh/chart: grafana-7.3.11
  name: my-release-grafana
  namespace: default
  resourceVersion: "26312"
  uid: 2288c75a-74d2-480a-8e5a-8f35fdc475c7
