---
- name: Deploy applications to Kubernetes
  hosts: localhost
  tasks:
    - name: Deploy Apache application
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/web_deploy.yml') }}"
        kubeconfig: "/home/cheikh/.kube/config"

    - name: Deploy MySQL application
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/db_deploy.yml') }}"
        kubeconfig: "/home/cheikh/.kube/config"

    - name: Create service for Apache application
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/web_services.yml') }}"
        kubeconfig: "/home/cheikh/.kube/config"

    - name: Create service for MySQL application
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/db_services.yml') }}"
        kubeconfig: "/home/cheikh/.kube/config"
